version: '3.8'

services:
  backend:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      - MONGO_URI=${MONGO_URI}  
    volumes:
      - .:/app  
      - /app/node_modules  

networks:
  app-network:
    driver: bridge
